### ISSUE TITLE
Coursera Code of Honor

### ISSUE THREAD

**Issue by tOverney** [Shekeen/Scala-Reactive-Programming-Class#1]
Dear @Shekeen !
Posting solutions is against the coursera code of honor.
Please remove that repo or make it private!

Tristan,
staff for the reactive programming mooc.

**Comment by Shekeen** [comment]
Sorry about that, I published it after the course was over.
I thought that the tasks in the next sessions will be different, guess that's not the case.
I will close the repo ASAP.

**Comment by tOverney** [comment]
thanks
